# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      # Generate Sphinx conf.py using JupyterBook
      - "jupyter-book config sphinx book/website/en"
      # Write pathways modifications
      # - "pathways book/website"

sphinx:
  configuration: book/website/en/conf.py

# formats:
#    - pdf
#    - epub

python:
  install:
    - requirements: book/website/requirements.txt
